# -*- coding: utf-8 -*-
"""Python_basics_Manchi Jyotsna.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18HFRaVzcunjA7H3vyvwBRhaCag09Md2M
"""

#Task 1
Name = "Jyotsna"
Age = 25
Height = 5.2
is_student = True
print(Name, Age, Height, is_student)

#task 2
print(f"name:{Name} |age:{Age} |height:{Height} |is_student:{is_student}")

#Task 3
Age_months = Age * 12
Age_days = Age * 365
Remainder = Age % 7
Age_square = Age ** 2
print ("Age in months:", Age_months)
print ("Age in days:", Age_days)
print ("Remainder when age divided by 7:", Remainder)
print ("Age squared:", Age_square)